#!/usr/bin/env bash
# Update Nginx configuration to listen on port 80
# Restart Nginx service to apply changes

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
