#!/usr/bin/env bash
# Group visitors by IP and HTTP status code and display the data
# Format: OCCURENCE_NUMBER IP HTTP_CODE
# Ordered from the greatest to the lowest number of occurrences

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
