#!/usr/bin/env bash
# This script displays "Best School" 10 times, and on the 9th iteration, it displays "Hi"

cun=0

while [ $cun -lt 10 ]; do
  if [ $cun -eq 8 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((cun++))
done
